[DOC] add list of supported softwares
ReproNim/neurodocker pull request #587
Opened 2023-11-10 11:59 UTC by Remi-Gau

- closes #580 

- add script to generate list of supported softwares from the templates
- add url for software in template schema
- add url for each software
- point readme to list of softwares

2023-11-10 18:46 UTC, kaczmarj requested changes
fantastic!! this will be a great resource for users.

could you please also add the "url" key to the template in the "add template" documentation page?

https://github.com/ReproNim/neurodocker/blob/29ecd7ad4740ee3db6d78b3e3071e776562674ee/docs/user_guide/add_template.rst?plain=1#L17-L21

2023-11-12 10:21 UTC, Remi-Gau commented
Done in f158b7e26ec7c6114fbf09678943aaf40df77a65

2023-11-12 14:37 UTC, kaczmarj approved these changes

2023-11-12 14:37 UTC, kaczmarj commented
thanks @Remi-Gau ! looks great on my end. thanks again. this list will definitely help lots of people.

2023-11-12 15:23 UTC, merged